### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/obel#216]
Branch Name: **`chore/upgrade-dependencies`**

**Comment by ri7nz** [comment]
@zainfathoni  I think we can use `conventional commits`, so the branch name is `chore/upgrade-dependencies` , wdyt?

**Comment by zainfathoni** [comment]
Sure, thank you for the suggestion.
I've updated the description.

**Comment by ri7nz** [comment]
@zainfathoni  I'm start to solve this is issue. :rocket:

**Comment by zainfathoni** [comment]
- Thanks a lot! 🙏
